[package]
name = "fx-markers"
version = "0.1.0"
authors = ["The Mozilla Project Developers"]
edition = "2021"
license = "MPL-2.0"

[dependencies]
profiler-macros = { path = "./macros" }
serde = { version = "1.0", features = ["derive"] }
